# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_access_king_admin', 'KINGADMIN 首页'), ('can_table_index', 'KINGADMIN_单个app'), ('can_table_list', 'KINGADMIN_app中 列表查看'), ('can_access_obj_add', 'KINGADMIN_app中 添加'), ('can_access_obj_add_post', 'KINGADMIN_app中 添加'), ('can_access_table_change', 'KINGADMIN_修改'), ('can_access_table_change_post', 'KINGADMIN_修改保存'), ('can_access_obj_delete', 'KINGADMIN_删除'), ('can_access_obj_delete_post', 'KINGADMIN_删除确认'), ('can_access_password_reset', 'KINGADMIN_修改密码'), ('can_access_password_reset_post', 'KINGADMIN_修改密码保存'), ('can_sales_index', '销售首页'), ('can_access_customer_list', '查看客户库'), ('can_access_customer_detail', '客户信息详情'), ('can_access_customer_detail_post', '客户信息详情修改'), ('can_access_customer_add', '客户信息添加'), ('can_access_customer_add_post', '客户信息添加保存'), ('can_access_customerfollowup_list', '销售 客户信息跟记录'), ('can_access_customerfollowup_detail', '销售 客户信息跟进详情修改'), ('can_access_customerfollowup_detail_post', '销售 客户信息跟进详情修改保存'), ('can_teacher_classes_customerfollowup_add', '销售 客户信息跟进添加'), ('can_teacher_classes_customerfollowup_add_post', '销售 客户信息跟进添加保存'), ('can_access_enrollment', '报名流程一'), ('can_access_enrollment_post', '报名流程一修改'), ('can_teacher_index', '讲师首页'), ('can_my_teacher_classes', '讲师查看我的班级'), ('can_teacher_classes_courserecord', '讲师班级上课列表'), ('can_teacher_classes_courserecord_post', '讲师班级上课列表批量创建'), ('can_teacher_classes_courserecord_change', '班级课节'), ('can_teacher_classes_courserecord_change_post', '班级课节保存'), ('can_teacher_classes_courserecord_add', '班级上课添加'), ('can_teacher_classes_courserecord_add_post', '班级上课添加保存'), ('can_teacher_classes_studyrecord', '班级学员上课记录'), ('can_teacher_classes_studyrecord_post', '班级学员上课记录保存'), ('can_teacher_classes_studyrecord_change', '讲师班级学员课节 学习记录'), ('can_teacher_classes_studyrecord_change_post', '讲师班级学员课节 学习记录保存'), ('can_financial_index', '财务首页'), ('can_financial_not_audit', '财务待审核'), ('can_financial_contract_review', '财务审核'), ('can_financial_enrollment_rejection', '财务驳回'), ('can_financial_payment', '财务缴费'), ('can_financial_payment_post', '财务缴费确认'), ('can_student_index', '学员首页'), ('can_access_my_course', '学员查看我的课程'), ('can_access_studyrecords', '学员学习记录'), ('can_access_homework_detail', '学员作业详情'), ('can_upload_homework', '学员作业提交')), 'verbose_name_plural': '帐号表'},
        ),
    ]
