# Generated by Django 2.0.6 on 2018-07-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menuses',
            field=models.ManyToManyField(blank=True, to='crm.FirstLayerMenu', verbose_name='一层菜单'),
        ),
    ]
