# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20170928_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'verbose_name_plural': '合同表'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '帐号表'},
        ),
        migrations.AlterField(
            model_name='classlist',
            name='contract',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ContractTemplate'),
        ),
    ]
