# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20171002_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrecord',
            name='score',
            field=models.SmallIntegerField(blank=True, choices=[(100, 'A+'), (90, 'A'), (85, 'B+'), (80, 'B'), (75, 'B-'), (70, 'C+'), (60, 'C'), (40, 'C-'), (-50, 'D'), (-100, 'COPY'), (0, 'N/A')], default=0, null=True),
        ),
    ]
