# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20171002_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name': '学习记录表', 'verbose_name_plural': '学习记录表'},
        ),
    ]
