# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_userprofile_stu_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_chang', '权限测试'),), 'verbose_name_plural': '帐号表'},
        ),
    ]
