# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20171009_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_chang', '权限测试'), ('can_access_my_course', '查看我的班级'), ('can_access_customer_list', '查看客户库'), ('can_access_customer_detail', '客户信息详情'), ('can_access_studyrecords', '学员学习记录'), ('can_access_homework_detail', '学员作业详情'), ('can_upload_homework', '学员作业提交')), 'verbose_name_plural': '帐号表'},
        ),
    ]
